### ISSUE TITLE
Any plans to publish it to the NuGet feed?

### ISSUE THREAD

**Issue by AndreyBespamyatnov** [reactivemarbles/ObservableEventsSourceGenerator#26]

**Comment by glennawatson** [comment]
Yeah this week is the plan. Just want to put all the dependabot PRs out and run the tests.

**Comment by AndreyBespamyatnov** [comment]
Let me know if you need any help since I want to use that approach for our Xamarin project and we want to use version 5 of xamarin)

**Comment by glennawatson** [comment]
See https://www.nuget.org/packages/ReactiveMarbles.ObservableEvents.SourceGenerator/
